version: "3"

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment: # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    container_name: mysqlServer
    expose:
      - 3306
    networks:
      - app-tier
    volumes:
      - .\mysql:/var/lib/mysql
      - .\mysql_config:/etc/mysql

  python_app:
    image: python:latest
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    links:
      - mysql_db:mysql
    #    depends_on:
    #      - mysql_db
    networks:
      - app-tier
    volumes:
      - .\code:/code
    command: tail -f /dev/null

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  mysql:
  mysql_config:
  code:

networks:
  app-tier:
    driver: bridge
